name: Gogo13
markdown: kramdown
highlighter: rouge
remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

ga_tracking: UA-47988407-1

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/go717franciswang/go717franciswang.github.io" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree"
